CFLAGS=-fPIC -std=c99 -fopenmp 
ADD_CFLAGS=-DHAVE_OMP_H=1 -DHAVE_CL_OPENCL_H=1


all: grav_pot.so grav_pot_cuda.so cummean.so #grav_pot_cuda.so grav_pot.so


grav_pot.so: grav_pot.o
	gcc -fopenmp -shared -lm -lOpenCL -o .libs/libgrav_pot.so .libs/libgrav_pot.o
grav_pot.o:
	gcc -fopenmp -c -fPIC $(ADD_CFLAGS) -o .libs/libgrav_pot.o src/grav_pot.c
grav_pot_cuda.so:
	nvcc --compiler-options '-fPIC' -o .libs/libgrav_pot_cuda.so --shared src/grav_pot.cu

cummean.so: cummean.o
	gcc -fopenmp -shared -o .libs/libcummean.so .libs/libcummean.o
cummean.o:
	gcc -fopenmp -c -fPIC $(ADD_CFLAGS) -o .libs/libcummean.o src/cummean.c

clean:
	test -f grav_pot.o && rm grav_pot.o || true
	test -f grav_pot.so && rm grav_pot.so || true
	test -f grav_pot_cuda.o && rm grav_pot_cuda.o || true
	test -f grav_pot_cuda.so && rm grav_pot_cuda.so || true
	test -f cummean.o && rm cummean.o || true
	test -f cummean.so && rm cummean.so || true
