stages:
  - deploy

pages:
  stage: deploy
  image: python:3.9-slim
  before_script:
    - apt-get update && apt-get install make build-essential automake --no-install-recommends -y
    - python -m pip install sphinx furo
    - python -m pip install -r requirements.txt
  script:
    - cd ffi && ./configure && make clean && make && cd ..
    - cd docs && make html
  after_script:
    - mv docs/build/html/ ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
